### ISSUE TITLE
Why does the force option break the page?

### ISSUE THREAD

**Issue by stefkes** [HTMLMin/Laravel-HTMLMin#103]
When I apply the `force` setting my pages break and I'd like to figure out why. When I check the class, it seems like the `containsBadHtml` implies there is "bad html"

Below is a snippet from a blade template that doesn't get minified. It uses a translation library that uses a syntax which perhaps is considered as "bad html" - is this the case? Is there any way I can work around this?

```
<p class='home_description'>@lang('Some text :placeholder1.', 
['placeholder1' => "<a href='" . Trans::getLocalizedURL($current_lang, Trans::transRoute('routes.name')) . "/some-value' class='view_full'>" . __('some string') . "</a>",])
</p>```

**Comment by GrahamCampbell** [comment]
Forcing it will force it to minify, even when the minifier can't do it safely, so it may break the page.

**Comment by GrahamCampbell** [comment]
I don't see the need to work around. This package minifies where possible, to get good results. It does not attempt to achieve minimal bytes. If you want that, use the http middleware shipped with this package.

**Comment by stefkes** [comment]
I was wondering why it can't minify safely, just out of curiosity. Is it because of the syntax I posted, or you have no easy way of telling?
