### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by rjsworking** [HTMLMin/Laravel-HTMLMin#105]
Hi

Update to L56, please.

Thanks in advance
Cheers

**Comment by rodrigopedra** [comment]
PR #108  was merged to accomplish this!

The only thing missing is tagging a release... 

But you can use a specific commit in your composer file, if you wish [see this answer on stackoverflow](https://stackoverflow.com/a/21316829).

**Comment by Tickthokk** [comment]
I hope we get a tag soon.  Doing this doesn't feel good 😛 

```
"htmlmin/htmlmin": "dev-master#e3d5e0b1e5019eb701ac68945510518b62d3ff50"
```

**Comment by FarshadGhanbari** [comment]
for laravel 5.6 :
https://github.com/FarshadGhanbari/laravel-htmlmin
