### ISSUE TITLE
Situations Where Optimization fails

### ISSUE THREAD

**Issue by WisdomEye** [HTMLMin/Laravel-HTMLMin#117]
Seems with single blade (no include or yield) works pretty nice.

But, using blade as cascade theme (many includes or yield from database), only the final blade file get optimized.

If I set on app\Http\Kernel.php:

`\HTMLMin\HTMLMin\Http\Middleware\MinifyMiddleware::class,`

The final result is partial minified, not same as single blade file without include or yield.

**Comment by WisdomEye** [comment]
I have found another situation:

The script does not understand the structure of:

[http://schema.org/docs/full.html](http://schema.org/docs/full.html)

Then will mark as bad html and make no more optimizations.

**Comment by WisdomEye** [comment]
Another situation:

If the CSRF token is on Head, the optimization not happen:

`		<script>
			window.Laravel = {!! json_encode(['csrfToken' => csrf_token()]); !!}
		</script>`

**Comment by srmklive** [comment]
Closing

**Comment by NicoEngler** [comment]
Why was this closed without a solution? The html code I inject from a database also does not get minified. Any info would be useful.
