### ISSUE TITLE
With custom blade directive

### ISSUE THREAD

**Issue by lloricode** [HTMLMin/Laravel-HTMLMin#127]
HTMLMin/Laravel-HTMLMin: v5.7.0
laravel/framework: 5.7.22

![screenshot from 2019-01-25 09-36-25](https://user-images.githubusercontent.com/8251344/51719533-be2e7b80-2084-11e9-81a3-524d70e1215f.png)

in service provider
![screenshot from 2019-01-25 09-36-34](https://user-images.githubusercontent.com/8251344/51719535-bff83f00-2084-11e9-9ed8-54da94c25194.png)

in blade
![screenshot from 2019-01-25 09-38-15](https://user-images.githubusercontent.com/8251344/51719578-f5049180-2084-11e9-801c-98f968adf8f9.png)

**Comment by radu-at** [comment]
Same problem here, this plugin doesn't work if there are custom blade directive in templates.

**Comment by guidocella** [comment]
I solved this issue by replacing

```php
Blade::directive(
```

with
```php
$compiler = $this->app['htmlmin.compiler'];

$compiler->directive(
```

**Comment by lidoma** [comment]
Same issue with custom blade directives by third-party packages. Like [Blade-svg](https://github.com/adamwathan/blade-svg/issues)

**Comment by ImCheery** [comment]
Initialization of the MinifyCompiler does not transfer previously defined custom directives. The straightforward way (not the best or optimal one) is to add to the constructor of MinifyCompiler one line:
` $this->customDirectives = \Blade::getCustomDirectives();`
