### ISSUE TITLE
laravel/framework 5.8.* support

### ISSUE THREAD

**Issue by SHSharkar** [HTMLMin/Laravel-HTMLMin#129]
Hello,

Laravel just upgraded to v5.8. Could you please help to upgrade the package to compatible with the new version?

```
Your requirements could not be resolved to an installable set of packages.

Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev, v5.8.0].
 
Failed to update packages for  ./composer.json.
```

**Comment by awgul** [comment]
Hey,

It would be great.

**Comment by brianwozeniak** [comment]
Please update composer.json to support Laravel 5.8.  Was released a few days ago now!

**Comment by SHSharkar** [comment]
Thanks, @brianwozeniak  for the prompt response.
