### ISSUE TITLE
Packagist must be update for Laravel 5.8

### ISSUE THREAD

**Issue by whthT** [HTMLMin/Laravel-HTMLMin#134]
As of now, the packagist supports the Laravel 5.7 version in the latest release. I ask that this be corrected.

**Comment by lloricode** [comment]
@GrahamCampbell

**Comment by GrahamCampbell** [comment]
I'm no longer maintaining this package. It's been handed over to new maintainers.

**Comment by jdavidbakr** [comment]
@GrahamCampbell - you are the account linked at Packagist - I believe you are the only one who can change the Packagist settings to the new way github requires.

**Comment by KevAtFathom** [comment]
@srmklive - are you the main maintainer now for this repo?
If so could you contact @GrahamCampbell & between you work out how to update the package on Packagist please.

**Comment by srmklive** [comment]
Package is already updated for Laravel 5.8

**Comment by KevAtFathom** [comment]
@srmklive - https://packagist.org/packages/htmlmin/htmlmin is still at 5.7 not 5.8

**Comment by jdavidbakr** [comment]
It is not updated on packagist https://packagist.org/packages/htmlmin/htmlmin

**Comment by eamirgh** [comment]
@srmklive most developers use packagist to install packages from composer,
please create a new one or update previous.
thanks!

**Comment by srmklive** [comment]
Sorry for responding late. In

**Comment by GrahamCampbell** [comment]
@srmklive Please go to https://packagist.org/trigger-github-sync/. This should fix the issue with packagist.

**Comment by srmklive** [comment]
Packagist is updated & is showing 5.8.0 as latest version.

**Comment by GrahamCampbell** [comment]
Packagist is still reporting the webhook has not been updated.

**Comment by whthT** [comment]
This should not be so difficult to create a new release that should be done

```bash
git tag -a 5.8.0 -m "v5.8.0"
git push --tags
````

**Comment by srmklive** [comment]
Webhook has been updated for Packagist.

**Comment by whthT** [comment]
God thank u
