### ISSUE TITLE
Prepare for Laravel 6.0

### ISSUE THREAD

**Issue by rcerljenko** [HTMLMin/Laravel-HTMLMin#137]
You should probably raise the version flags to 6.0 for Laravel  :)

**Comment by marcelogarbin** [comment]
any news?

**Comment by maprangsoft** [comment]
please update for support laravel 6

**Comment by AntoineLX** [comment]
I second this, need it on many L6 projects.

**Comment by jcsoriano** [comment]
Bumping this up, also hoping this gets upgraded
