### ISSUE TITLE
Prepare for Laravel 6.1

### ISSUE THREAD

**Issue by rcerljenko** [HTMLMin/Laravel-HTMLMin#140]
Please raise the version flags for Laravel 6.1+

**Comment by vserdobintsev** [comment]
Please fix bug with custom Blade directives!!!!

**Comment by rcerljenko** [comment]
@timonweber this would be great because there's Laravel 6.2 already and I'm sick of waiting every time there's a new Laravel version for this package to update...

**Comment by fridlev** [comment]
Any changes this will be updated for the current version 6.3?

**Comment by srmklive** [comment]
Package has been updated to support Laravel 6.1 & beyond.
