### ISSUE TITLE
Prepare for Laravel 8

### ISSUE THREAD

**Issue by rcerljenko** [HTMLMin/Laravel-HTMLMin#154]
Laravel 8 will be released on September 8th. Can we check that the library is safe to work with Laravel 8 and update the composer version flags accordingly?

**Comment by rcerljenko** [comment]
ping

**Comment by Calinou** [comment]
In the meantime, you can update your `composer.json` to use the following version:

```json
"htmlmin/htmlmin": "dev-master#e67fe976e3fd1e92568341ce84f338fa4c0ffc47"
```

Make sure to replace this with a tagged version once it's officially released.

**Comment by Referion** [comment]
Are you planning on releasing the new tagged version (with Laravel 8 support) anytime soon?
Thanks!

**Comment by rcerljenko** [comment]
ping!

**Comment by dmyers** [comment]
Anyone know of a more updated package to switch to?

**Comment by u01jmg3** [comment]
https://github.com/HTMLMin/Laravel-HTMLMin/blob/e67fe976e3fd1e92568341ce84f338fa4c0ffc47/src/HTMLMinServiceProvider.php#L165-L170

Is anyone else experiencing the following error from Laravel when running `php artisan package:discover --ansi` due to the code above? This is since the move to Laravel 8.

```
In Container.php line 811:
  Target class [view] does not exist.

In Container.php line 809:
  Class view does not exist
```

**Comment by Calinou** [comment]
cc @srmklive

**Comment by dmyers** [comment]
It looks like this may be done already it looks like? https://github.com/HTMLMin/Laravel-HTMLMin/commit/e67fe976e3fd1e92568341ce84f338fa4c0ffc47

**Comment by Calinou** [comment]
@dmyers It was done already, but a release needs to be tagged so it can be referenced more easily in Composer.

**Comment by dmyers** [comment]
Oh good catch @Calinou I didn't see that. Hopefully that can be tagged soon.

**Comment by srmklive** [comment]
Hi everyone,

My mistake i didn't tag the release as soon as i added support for Laravel 8.
