### ISSUE TITLE
laravel8: "Class view does not exist" after install

### ISSUE THREAD

**Issue by iArtem88** [HTMLMin/Laravel-HTMLMin#163]
>After:
      composer require htmlmin/htmlmin
      composer dump-autoload

>Run:
      php artisan

>Result:

      In Container.php line 875:
                                             
        Target class [view] does not exist.  
      
      In Container.php line 873:
                                   
        Class view does not exist  

>Application Service Providers (3rd party):
     
        Intervention\Image\ImageServiceProvider::class,
        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
        Laravel\Socialite\SocialiteServiceProvider::class,
        Maatwebsite\Excel\ExcelServiceProvider::class,
        Petehouston\Tinymce\TinymceServiceProvider::class,
        Irazasyed\LaravelGAMP\LaravelGAMPServiceProvider::class,
        Fideloper\Proxy\TrustedProxyServiceProvider::class,
        Buzz\LaravelGoogleCaptcha\CaptchaServiceProvider::class,
        Greggilbert\Recaptcha\RecaptchaServiceProvider::class,

> no effect after bootstrap/cache was cleared

**Comment by u01jmg3** [comment]
The yet unmerged PR #162 looks to fix this

**Comment by u01jmg3** [comment]
@srmklive: this issue can be closed
