### ISSUE TITLE
lot of @break in views

### ISSUE THREAD

**Issue by MalikOvaiz** [HTMLMin/Laravel-HTMLMin#78]
I have integrated GrahamCampbell/Laravel-HTMLMin in my project and i get lot of @break in my page
please check attached image

![screenshot from 2017-07-05 09-09-25](https://user-images.githubusercontent.com/10618104/27848856-b5b7d886-6161-11e7-950f-21bbe14e650a.png)

**Comment by srmklive** [comment]
Can you provide further details as to why this issue is happening?

**Comment by Rubemlrm** [comment]
@MalikOvaiz are you still having that problem ?

**Comment by srmklive** [comment]
@MalikOvaiz Kindly provide code sample, so i can work on the fix for the issue you mentioned.

**Comment by ctf0** [comment]
@srmklive hi there, am having a slight similar issue with custom tags like `@routes` which is used by https://github.com/tightenco/ziggy

**Comment by MalikOvaiz** [comment]
@srmklive and @Rubemlrm  i am not using this package anymore; I switched to Gulp due to short deadline.Well, i was using smarty blade engine in my project.
