### ISSUE TITLE
Alias/Facade and Service Providers in README are wrong

### ISSUE THREAD

**Issue by rattfieldnz** [HTMLMin/Laravel-HTMLMin#83]
Hi there,

Have just finished installing and configuring this package to a project, and found out the Facade/Provider lines mentioned did not work for me. 

**Facade/Alias**
I replaced `'HTMLMin' => HTMLMin\HTMLMin\Facades\HTMLMin::class,` with `'HTMLMin' => GrahamCampbell\HTMLMin\Facades\HTMLMin::class,`

**Service Provider**
I replaced `HTMLMin\HTMLMin\Http\Middleware\MinifyMiddleware` with `GrahamCampbell\HTMLMin\HTMLMinServiceProvider::class`.

Both substitutes mentioned above worked in my case. I just would like to confirm if this is correct?

**Comment by Benjyclay** [comment]
This is updated in the repo but just needs to be updated on Packagist @GrahamCampbell can you do this?

**Comment by GrahamCampbell** [comment]
I no longer am in charge here. I've updated the readme for the upcoming major release, but I've handed over the project lead now.

**Comment by GrahamCampbell** [comment]
Whenever the next major release is tagged by the new author, the new readme will work.

**Comment by rattfieldnz** [comment]
Thanks for replying Graham and Benjyclay. This is relatively minor; however, updating the Packagist details would really help prevent other developers getting tripped up by it. 

Should I close this issue?

**Comment by secrethash** [comment]
Project's `composer.json` is not updated in `v4.5` as it was updated after the release in master. Please Draft a new Release.

**Comment by srmklive** [comment]
I have tagged a new release `v4.5.1`.

**Comment by GrahamCampbell** [comment]
> I have tagged a new release v4.5.1.

Reverted. The next release absolutely must be v5.0.0.
