### ISSUE TITLE
Skip @php minification

### ISSUE THREAD

**Issue by secrethash** [HTMLMin/Laravel-HTMLMin#86]
Minifier should skip the minification of `@php` to `@endphp` blade tags.

**Comment by srmklive** [comment]
@secrethash Can you specify any scenarios where this might be needed?

**Comment by secrethash** [comment]
In the blade files. Actually, this happened when I set the `'force'=>true`.

_Sent from my Lenovo K50a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by srmklive** [comment]
If you set `'blade' => false`, does the same issue still occurs?

**Comment by secrethash** [comment]
Nope, currently I have set both of them to false and I am using the **middleware minification method**. As it minifys the HTML only, no errors are generated.

_Sent from my Lenovo K50a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by srmklive** [comment]
@secrethash OK. I will look into this, and hopefully will have a fix available soon.
