### ISSUE TITLE
laravel 5.5

### ISSUE THREAD

**Issue by vesper8** [HTMLMin/Laravel-HTMLMin#87]
yours is one of few packages which doesn't work with 5.5 out of the box. Probably just need to update the dependencies to include 5.5.* so should be very easy fix. I know L5.5 isn't out yet but a lot of people are already using it and a lot of packages have been getting ready for it.

I've commented it out for now but just letting you know. Thanks!

**Comment by srmklive** [comment]
Already merged #88 which adds support for 5.5
