### ISSUE TITLE
NEXT RELEASE MUST BE V5.0.0

### ISSUE THREAD

**Issue by GrahamCampbell** [HTMLMin/Laravel-HTMLMin#89]
This package follows semver. This promise was made initially, and cannot be broken.

**Comment by GrahamCampbell** [comment]
I've reverted the tag of v4.5.1.

**Comment by srmklive** [comment]
Thanks @GrahamCampbell for this. Will keep this pattern in mind going forward

**Comment by GrahamCampbell** [comment]
Also, note there's a branch alias in the composer.json. It tells you the current master represents dev on 5.0.x. In the future, you'll wanna bump that alias as dev represents later versions.
