### ISSUE TITLE
blade changes has no effect

### ISSUE THREAD

**Issue by slillo** [HTMLMin/Laravel-HTMLMin#91]
After I've enabled htmlmin.blade I'm not able to see changes I make to blade files on browser. 

I already tryied to disable opcache in php.ini, changed cache driver in .env and to delete cache (php artisan cache:clear) and views (php artisan view:clear). 

I'm working on localhost, so it's not a problem related to different environment times.

**Comment by garbinmarcelo** [comment]
@slillo Sorry to answer after so long, but how did you solve this problem?
