### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by leovanhaaren** [HTMLMin/Laravel-HTMLMin#92]
Can you please make it Laravel 5.5 compatible? Looks like it won't be too much work.

**Comment by stedop** [comment]
Judging by the repo, it has already been done. It just installed for me.

I had to 

- update my composer,json to use htmlmin/htmlmin: ^5.0 

and

-  update my config/app.php file to change the service provider to `\HTMLMin\HTMLMin\HTMLMinServiceProvider::class`

Hope this is of help.
