### ISSUE TITLE
textarea minify issue

### ISSUE THREAD

**Issue by hamrosafari15** [HTMLMin/Laravel-HTMLMin#95]
whenever the minifier encounters the textarea html tag then it skips the minification process.. your package is very useful.. please fix it as soon as possible.

**Comment by GrahamCampbell** [comment]
This is not a bug, but is the intentional behaviour. It's not safe to use our fast minification of textarea fields.

**Comment by hamrosafari15** [comment]
oh ok.. is there any way to let minifier know to skip that textarea field html line??

**Comment by GrahamCampbell** [comment]
The minifier does skip it, it skips the file.

**Comment by hamrosafari15** [comment]
just need to skip the textarea line of code inside file.. can we do that??
