### ISSUE TITLE
Error install package on laravel 5.4

### ISSUE THREAD

**Issue by serverfire** [HTMLMin/Laravel-HTMLMin#97]
I got follownig error when install your package and add providers:
  [Symfony\Component\Debug\Exception\FatalThrowableError]      
  Undefined constant 'HTMLMin\HTMLMin\HTMLMinServiceProvider' 
my laravel version is: 5.4.36
php 7.1.8
"htmlmin/htmlmin": "^5.0"

**Comment by GrahamCampbell** [comment]
Looks like you have missed single quotes surrounding the string, or the `::class` on the end.

**Comment by srmklive** [comment]
You should add it like this in 5.4:

```
HTMLMin\HTMLMin\HTMLMinServiceProvider::class
```
in the `providers` section in file `config/app.php`
